name: API CI
# on: [push] Si es un proyecto normal
on: #Cuando es monorepo, es decir, multiples proyectos en uno solo
  push:
    paths:
      - "./api/**"
      - ".github/workflows/api-ci.yml"

defaults: #Cuando es monorepo es decir, multiples proyectos en uno solo
  run:
    working-directory: ./api

jobs:
  lint:
    runs-on: ubuntu-latest
    name: ESLint
    steps:
        - name: 👍 Checkout
          uses: actions/checkout@v2

        - name: 📥 Install Dependencies
          run: npm i

        - name: 🌹 ESLint
          run: npm run lint

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'npm'
          cache-dependency-path: ./api/package-lock.json
      - name: install
        shell: bash
        run: npm i
      - name: run unit test
        shell: bash
        run: npm run test
  e2e:
    runs-on: ubuntu-latest
    container:
      image: node:14

    services:
      mongo-e2e:
        image: mongo:4.4
        ports:
          - 27017:27017
        env:
            MONGO_INITDB_ROOT_USERNAME: test
            MONGO_INITDB_ROOT_PASSWORD: test123

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install
        shell: bash
        run: npm i
      - name: run e2e
        shell: bash
        run: npm run test:e2e
        env:
          MONGO_DB_NAME: demo
          MONGO_URL: mongodb://test:test123@mongo-e2e:27017?retryWrites=true&writeConcern=majority

